# Generated by Django 2.2.3 on 2019-10-14 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_delete_answerusercomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='dashboard.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_user_comment',
            },
        ),
    ]
