# Generated by Django 2.2.3 on 2020-03-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_website', '0002_contactussubmission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactussubmission',
            table='contact_us_submission',
        ),
    ]
