# Generated by Django 2.2.3 on 2020-03-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_website', '0004_auto_20200328_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactussubmission',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
