# Generated by Django 2.2.3 on 2020-06-08 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_website', '0005_auto_20200328_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerusercomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
