# Generated by Django 2.1.1 on 2018-10-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.IntegerField()),
                ('student_age', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('question_topic', models.CharField(max_length=100)),
                ('question_form', models.CharField(max_length=100)),
                ('question_language', models.CharField(max_length=100)),
                ('contributor', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('local_language', models.CharField(max_length=100)),
                ('medium_language', models.CharField(max_length=100)),
                ('question_submission_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
