# Generated by Django 2.2.3 on 2019-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='submission_id',
            new_name='dataset_id',
        ),
    ]
