# Generated by Django 2.1.1 on 2018-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181004_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contributor_role',
            field=models.CharField(default='test_user', max_length=100),
            preserve_default=False,
        ),
    ]
