# Generated by Django 2.2.3 on 2019-09-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_answerdraft'),
        ('dashboard', '0003_answercomment'),
    ]

    operations = [
    ]
