# Generated by Django 2.1.5 on 2019-03-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190305_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_questions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
