# Generated by Django 2.1.2 on 2018-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_question_contributor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_form',
            new_name='question_format',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_english',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='submitted_in_question_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_submission_date',
            field=models.DateTimeField(),
        ),
    ]
