# Generated by Django 2.1.5 on 2019-03-22 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_question_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(default='', max_length=100)),
                ('student_class', models.CharField(default='', max_length=100)),
                ('question_text', models.CharField(max_length=1000)),
                ('question_text_english', models.CharField(default='', max_length=1000)),
                ('question_format', models.CharField(max_length=100)),
                ('question_language', models.CharField(max_length=100)),
                ('contributor', models.CharField(max_length=100)),
                ('contributor_role', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('medium_language', models.CharField(max_length=100)),
                ('curriculum_followed', models.CharField(default='', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('published_source', models.CharField(default='', max_length=200)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('question_asked_on', models.DateField(null=True)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('submission_id', models.IntegerField()),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_archive',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_english',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='question',
            name='curated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='curated_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
