# Generated by Django 2.2.3 on 2019-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20190909_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_english',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
