# Generated by Django 2.1.2 on 2018-10-28 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181021_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='question',
            name='published_magazine',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='student_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='student_class',
            field=models.IntegerField(default=0),
        ),
    ]
