# Generated by Django 2.1.5 on 2019-03-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190322_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
                ('answered_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_answers', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='approved_answers', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='dashboard.Question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
