# Generated by Django 2.1.2 on 2018-10-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181028_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='published_magazine',
            new_name='published_source',
        ),
    ]
