# Generated by Django 2.2.3 on 2019-10-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_answerusercomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerUserComment',
        ),
    ]
