# Generated by Django 2.1.5 on 2019-03-26 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncuratedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_method', models.CharField(max_length=50)),
                ('submission_id', models.IntegerField()),
                ('number_of_questions', models.IntegerField()),
                ('excel_sheet', models.CharField(max_length=100)),
                ('curated', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uncurated_submission',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
