# Generated by Django 2.1.2 on 2018-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181028_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_submission_date',
        ),
        migrations.AddField(
            model_name='question',
            name='question_asked_on',
            field=models.DateField(null=True),
        ),
    ]
