# Generated by Django 2.1.2 on 2018-11-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181029_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submitted_in_question_box',
        ),
    ]
