# Generated by Django 2.2.3 on 2019-12-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_delete_answerusercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_title', models.CharField(max_length=50)),
                ('credit_user_name', models.CharField(max_length=50)),
                ('is_user', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='dashboard.Answer')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='answer_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_credit',
            },
        ),
    ]
