# Generated by Django 2.1.5 on 2019-03-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190328_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='local_language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_topic',
        ),
    ]
