# Generated by Django 2.2.3 on 2019-12-16 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_article_articledraft_submittedarticle_translatedarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='articledraft',
            name='body',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articledraft',
            name='language',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articledraft',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submittedarticle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=100),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.SubmittedArticle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_comment',
            },
        ),
    ]
