# Generated by Django 2.2.3 on 2019-12-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191216_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='answer',
            new_name='article',
        ),
    ]
