# Generated by Django 2.1.2 on 2018-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181109_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_age',
        ),
        migrations.AddField(
            model_name='question',
            name='student_gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
