# Generated by Django 2.2.3 on 2020-01-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200108_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
