# Generated by Django 2.1.5 on 2019-04-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190329_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='approved_by',
        ),
    ]
