# Generated by Django 2.1.5 on 2019-04-09 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_answer_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
