# Generated by Django 2.1.2 on 2019-01-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181120_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_english',
            field=models.CharField(default='', max_length=500),
        ),
    ]
