# Generated by Django 2.2.3 on 2020-01-08 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200108_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercredit',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
