# Generated by Django 2.1.2 on 2019-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190101_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
