# Generated by Django 2.1.5 on 2019-04-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_answer_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_comment',
            },
        ),
    ]
