# Generated by Django 2.2.3 on 2020-01-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200108_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercredit',
            options={'ordering': ['id']},
        ),
    ]
