# Generated by Django 2.1.5 on 2019-05-14 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190514_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='encoded_by',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='encoded_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
