# Generated by Django 2.2.3 on 2020-01-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200108_1738'),
        ('dashboard', '0012_articledraft_publishedarticle_submittedarticle'),
    ]

    operations = [
    ]
