# Generated by Django 2.2.4 on 2020-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200108_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletranslation',
            old_name='article',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
    ]
