# Generated by Django 2.2.3 on 2020-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_merge_20200110_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(default='english', max_length=100),
        ),
    ]
