# Generated by Django 2.1.5 on 2019-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190514_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments_on_coding_rationale',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='question_topic_relation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_of_session',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='type_of_school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unencodedsubmission',
            name='submission_id',
            field=models.IntegerField(null=True),
        ),
    ]
