# Generated by Django 2.2.3 on 2020-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_answer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='language',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
