# Generated by Django 2.2.4 on 2020-01-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200113_1856'),
        ('dashboard', '0014_rename_translation_source_field'),
    ]

    operations = [
    ]
