# Generated by Django 2.1.5 on 2019-06-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190517_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='dashboard.Question')),
            ],
            options={
                'db_table': 'translated_question',
            },
        ),
    ]
