# Generated by Django 2.2.4 on 2020-01-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_merge_20200114_1349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articledraft',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publishedarticle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='submittedarticle',
            table=None,
        ),
    ]
