# Generated by Django 2.1.5 on 2019-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_translatedquestion'),
        ('dashboard', '0012_auto_20190429_1751'),
    ]

    operations = [
    ]
