# Generated by Django 2.2.3 on 2020-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_make_question_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercredit',
            name='credit_title_order',
            field=models.IntegerField(default=0),
        ),
    ]
