# Generated by Django 2.2.4 on 2020-01-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200114_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articletranslation', to=settings.AUTH_USER_MODEL),
        ),
    ]
