# Generated by Django 2.2.4 on 2020-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_make_translated_by_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
