# Generated by Django 2.2.4 on 2020-01-22 10:08

import dashboard.mixins.draftables
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_articletranslation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='questionarchive',
            old_name='question_language',
            new_name='language',
        ),
    ]
