# Generated by Django 2.2.4 on 2020-01-22 10:23

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_question_language_namechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatedquestion',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='translatedquestion',
            old_name='question_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='translatedquestion',
            old_name='updated_on',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='curriculum_followed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='translated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='translatedquestion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
