# Generated by Django 2.2.4 on 2020-01-22 11:20

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_mixinify_translatedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='dashboard.Answer')),
                ('status', models.IntegerField(default=-1)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField()),
                ('translated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answertranslation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
