# Generated by Django 2.2.4 on 2020-01-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_comment'),
        ('dashboard', '0022_answertranslation'),
    ]

    operations = [
    ]
