# Generated by Django 2.2.4 on 2020-01-25 10:51

import dashboard.mixins.draftables
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_merge_translations_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertranslation',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='dashboard.Answer'),
        ),
    ]
