# Generated by Django 2.2.3 on 2020-01-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_answercredit_credit_title_order'),
        ('dashboard', '0025_draftable_add_create_update_time'),
    ]

    operations = [
    ]
