# Generated by Django 2.2.8 on 2020-03-17 11:00

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_merge_20200127_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_asked_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionarchive',
            name='question_asked_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
