# Generated by Django 2.2.3 on 2020-06-08 22:34

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200424_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submitted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answercredit',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answertranslation',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answertranslation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlecredit',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articletranslation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='curated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='curated_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='encoded_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encoded_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionarchive',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatedquestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uncuratedsubmission',
            name='submitted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
