# Generated by Django 2.2.8 on 2020-04-27 12:45

import dashboard.mixins.draftables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_draftable_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
