# Generated by Django 2.2.13 on 2020-07-14 07:47

import dashboard.mixins.draftables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200609_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercredit',
            name='credit_user_name',
            field=models.CharField(max_length=100),
        )
    ]
