# Generated by Django 2.2.13 on 2020-07-14 07:49

import dashboard.mixins.draftables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20200714_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecredit',
            name='credit_user_name',
            field=models.CharField(max_length=100),
        )
    ]
