# Generated by Django 2.2.13 on 2020-08-26 12:07

import dashboard.mixins.draftables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200714_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        )
    ]
