# Generated by Django 2.2.13 on 2021-05-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200826_1737'),
        ('dashboard', '0031_answer_published_on'),
    ]

    operations = [
    ]
