# Generated by Django 3.2 on 2021-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_answer_published_on'),
        ('dashboard', '0033_auto_20200826_1737'),
    ]

    operations = [
    ]
