# Generated by Django 2.2.13 on 2021-05-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_merge_20210506_1439'),
        ('dashboard', '0034_merge_20210513_2226'),
    ]

    operations = [
    ]
