# Generated by Django 2.2.13 on 2021-06-07 17:16

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0034_merge_20210506_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTranslationCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_title', models.CharField(max_length=50)),
                ('credit_title_order', models.IntegerField(default=0)),
                ('credit_user_name', models.CharField(max_length=100)),
                ('is_user', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_credits', to='dashboard.Answer')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_translation_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answer_translation_credit',
                'ordering': ['credit_title_order'],
            },
        ),
        migrations.AlterField(
            model_name='answertranslation',
            name='language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English'), ('hi', 'हिंदी'), ('mr', 'मराठी'), ('ml', 'മലയാളം'), ('ta', 'தமிழ்'), ('te', 'తెలుగు')], default='en', max_length=100),
        ),
    ]
