# Generated by Django 4.2 on 2023-11-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_merge_20210510_1642'),
        ('dashboard', '0035_merge_20210529_2232'),
        ('dashboard', '0036_auto_20210608_1954'),
    ]

    operations = [
    ]
