# Generated by Django 2.2.2 on 2019-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0002_volunteerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrequest',
            name='expert_application',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='translator_application',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='writer_application',
            field=models.TextField(null=True),
        ),
    ]
