# Generated by Django 2.2.3 on 2019-08-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0003_auto_20190723_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='expert_application',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='translator_application',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='writer_application',
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='permission_requested',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='request_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='requested_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
