# Generated by Django 2.2.3 on 2019-09-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0005_profilesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='requested_by',
            new_name='user_id',
        ),
    ]
