# Generated by Django 2.2.3 on 2019-09-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_answerdraft'),
        ('sawaliram_auth', '0007_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='content_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookmarks', to='dashboard.Question'),
        ),
    ]
