# Generated by Django 2.2.3 on 2019-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0009_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='url',
            new_name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
