# Generated by Django 2.2.3 on 2019-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0011_auto_20190911_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
