# Generated by Django 2.2.3 on 2019-10-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0012_auto_20190911_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description_text',
            field=models.CharField(max_length=500),
        ),
    ]
