# Generated by Django 2.2.13 on 2020-07-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0020_auto_20200609_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrequest',
            old_name='permission_requested',
            new_name='permissions_requested',
        ),
    ]
