# Generated by Django 2.2.13 on 2020-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawaliram_auth', '0021_auto_20200718_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_bg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
